CREATE SCHEMA IF NOT EXISTS student30;


CREATE TABLE IF NOT EXISTS student30.H_SALE  (
    Sale_HK VARCHAR(50) PRIMARY KEY, 
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.H_CUSTOMER ( 
    Customer_HK VARCHAR(50) PRIMARY KEY, 
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.H_SHIPMENT (
    Shipment_HK VARCHAR(50) PRIMARY KEY, 
    H_Load_Source VARCHAR(50) NOT NULL,
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.H_PRODUCT (
    Product_HK VARCHAR(50) PRIMARY KEY, 
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.L_SALE (
    L_Sale_HK VARCHAR(50) PRIMARY KEY, 
    H_Sale_HK VARCHAR(50) NOT NULL REFERENCES student30.H_SALE(Sale_HK),
    H_Customer_HK VARCHAR(50) NOT NULL REFERENCES student30.H_CUSTOMER(Customer_HK),
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.L_PRODUCT (
    L_Product_HK VARCHAR(50) PRIMARY KEY, 
    H_Product_HK VARCHAR(50) NOT NULL REFERENCES student30.H_PRODUCT(Product_HK),
    H_Sale_HK VARCHAR(50) NOT NULL REFERENCES student30.H_SALE(Sale_HK),
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student30.L_SHIPMENT (
    L_Shipment_HK VARCHAR(50) PRIMARY KEY, 
    H_Shipment_HK VARCHAR(50) NOT NULL REFERENCES student30.H_SHIPMENT(Shipment_HK),
    H_Sale_HK VARCHAR(50) NOT NULL REFERENCES student30.H_SALE(Sale_HK),
    H_Load_Source VARCHAR(50) NOT NULL, 
    H_Load_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student30.S_DETAILS (
    H_Product_HK VARCHAR(50) NOT NULL REFERENCES student30.H_PRODUCT(Product_HK),
    Category TEXT,
    Sub_Category TEXT,
    Load_Date TIMESTAMP NOT NULL,
    S_Hash TEXT,
    Load_Source TEXT,
    CONSTRAINT pk_s_details PRIMARY KEY (H_Product_HK, Load_Date)
);

CREATE TABLE student30.S_CUSTOMER (
    H_Customer_HK VARCHAR(50) NOT NULL REFERENCES student30.H_CUSTOMER(Customer_HK),
    Postal_Code TEXT,
    Country TEXT,
    Region TEXT,
    State TEXT,
    City TEXT,
    Load_Date TIMESTAMP NOT NULL,
    S_Hash TEXT,
    Load_Source TEXT,
    CONSTRAINT pk_s_customer PRIMARY KEY (H_Customer_HK, Load_Date)
);